# Generated by Django 5.2.2 on 2025-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_owner_alter_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='link',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
