# Generated by Django 5.2.2 on 2025-09-08 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id_of_connected_player',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_room_id', models.IntegerField()),
                ('device_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'device_hash'], name='main_update_room_id_4c0423_idx'), models.Index(fields=['updated_at'], name='main_update_updated_92a450_idx')],
            },
        ),
    ]
