# Generated by Django 5.2.2 on 2025-09-08 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_room_id_of_connected_player_updatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='locations_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.locationsgroup'),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_of_players',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(3, 'Комната не может быть меньше 3 человек')),
        ),
    ]
