# Generated by Django 5.2.2 on 2025-09-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_room_locations_group_alter_room_num_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
