# Generated by Django 5.2.2 on 2025-09-08 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_locations_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='locations_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.locationsgroup'),
            preserve_default=False,
        ),
    ]
