# Generated by Django 5.2.2 on 2025-09-08 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_room_locations_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='num_of_players',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(3, message='Комната не может быть меньше 3 человек')),
        ),
    ]
