# Generated by Django 5.2.2 on 2025-09-08 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_room_num_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='num_of_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=3, message='Минимум 3 игрока')]),
        ),
    ]
