# Generated by Django 5.2.2 on 2025-09-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_room_num_of_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.locations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='spy_id',
            field=models.IntegerField(default=0),
        ),
    ]
