# Generated by Django 5.2.2 on 2025-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsgroup',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='link',
            field=models.SlugField(unique=True),
        ),
    ]
