# Generated by Django 5.2.2 on 2026-01-15 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_locationsgroup_name_alter_room_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_room_id', models.IntegerField()),
                ('device_hash', models.CharField(max_length=64)),
                ('location_to_show', models.ManyToManyField(blank=True, null=True, to='main.locations')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
        migrations.DeleteModel(
            name='UpdateHistory',
        ),
        migrations.AddIndex(
            model_name='roomconnection',
            index=models.Index(fields=['room', 'device_hash'], name='main_roomco_room_id_416c33_idx'),
        ),
    ]
