# Generated by Django 5.2.2 on 2026-01-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_roomconnection_delete_updatehistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id_of_connected_player',
        ),
    ]
